default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.10
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: "check-case-conflict"
      - id: "check-merge-conflict"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
      - id: "mixed-line-ending"
      - id: "detect-private-key"
      - id: "check-yaml"
      - id: "check-toml"
      - id: "check-json"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.11.2'
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: python
        types_or: [ python, pyi ]
        args: [ ]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: "2.9.2"
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: python
        types_or: [ python, pyi ]
        args: [ ]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: "2.9.2"
